In [1]:
import os
import pandas as pd

from business_entity_resolution.components.data_transformation import (
    DataTransformation
)

from business_entity_resolution.components.candidate_generation import (
    CandidateGeneration
)

In [2]:
train_dir = "../dataset/train"

source1 = pd.read_csv(
    os.path.join(train_dir, "train_source1.tsv"),
    sep="\t"
)

source2 = pd.read_csv(
    os.path.join(train_dir, "train_source2.tsv"),
    sep="\t"
)

source3 = pd.read_csv(
    os.path.join(train_dir, "train_source3.tsv"),
    sep="\t"
)

ground_truth = pd.read_csv(
    os.path.join(train_dir, "train_ground_truth.tsv"),
    sep="\t"
)

In [ ]:
#Generate the 100 random samples from S1 jiske upar experminet kar na 
matched_s1_ids = ground_truth[
    ground_truth["matched_entity_ids"].notna()
    & ground_truth["matched_entity_ids"].ne("")
]["source1_entity_id"]

s1_ids = matched_s1_ids.sample(
    n=100,
    random_state=42
)

s1_sample = source1[
    source1["entity_id"].isin(s1_ids)
].copy()

print("S1 sample shape:", s1_sample.shape)

S1 sample shape: (100, 4)

In [4]:
s1_sample.head()

,entity_id,business_name,business_address,country
2132,S1-793615008,Clairvoyant Record Private Limited,"1St Floor, Tamrakarmall, New Bus Stand, Sehore...",India
39889,S1-670305710,"Loudoun County Cultural Coalition, LLC","44023 Vaira Terrace, Loudoun County, VA",US
47137,S1-449306864,A Cure 2 All PLLC,"OK, 14840 60th Avenue E, Collinsville",US
62221,S1-574333023,Classic Life International Private Limited,"Singar Nagar, Uttar Pradesh, Lucknow, 569/Ka/195",India
64951,S1-476955207,Lambodar Softwares,"B-702, Shreeji Arcade B/H Bhulkabhavan School,...",India

In [5]:
#ab matching id nikalo
ground_truth_sample = ground_truth[
    ground_truth["source1_entity_id"].isin(s1_ids)
].copy()

positive_pairs = (
    ground_truth_sample
    .dropna(subset=["matched_entity_ids"])
    .assign(
        matched_entity_id=lambda df: df["matched_entity_ids"].str.split(",")
    )
    .explode("matched_entity_id")
)

positive_pairs["matched_entity_id"] = (
    positive_pairs["matched_entity_id"]
    .str.strip()
)

print("True positive pairs:", len(positive_pairs))
positive_pairs.head()

True positive pairs: 374

,source1_entity_id,matched_entity_ids,matched_entity_id
38151,S1-574333023,S2-441818910,S2-441818910
45726,S1-354889538,"S2-334019354,S2-405677992,S2-631087818,S3-7859...",S2-334019354
45726,S1-354889538,"S2-334019354,S2-405677992,S2-631087818,S3-7859...",S2-405677992
45726,S1-354889538,"S2-334019354,S2-405677992,S2-631087818,S3-7859...",S2-631087818
45726,S1-354889538,"S2-334019354,S2-405677992,S2-631087818,S3-7859...",S3-785969699